# Define workflow name
name: HTTP App Workflow

# Define Event & triggered branches
on:
  push: 
    branches:
      - main
      - master
      - "feature/**" # Can use regular expressions

  # pull_request: 
  #   branches:
  #     - main

  # Define Tasks/Jobs
jobs:
  test_and_build: # Name of job should be descriptive
    runs-on: ubuntu-latest # Define the runner (Virtual Machine) that will host the application

    steps: # Define the steps of build and test
      - name: clone code # Clone the code on the VM to build
        uses: actions/checkout@v5 

      - name: set up node js environment
        uses: actions/setup-node@v7 # Setup the node js run-time env with the specified version from the github actions marketplace
        with: 
          node-version: 24 # node --version → v24.18.0

      - name: install node js packages
        run: npm install

      # - name: run tests
      # - run: npm run test # Uses the test files

      - name: build source code
        run: npm run build

      - name: upload artifacts # Upload the compiled files and dependencies
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: | # Pipeline symbol for multiple values 
            dist/
            package.json
          if-no-files-found: error


  deploy: # Deploy to AWS EC2
    runs-on: ubuntu-latest 
    needs: test_and_build # This job will run after the test_and_build job is completed successfully to ensure that the compiled files and dependencies are available for deployment
    steps:
      - name: download artifacts # Download the compiled files and dependencies on the VM to deploy
        uses: actions/download-artifact@v4
        with: 
          name: source-code
          path: ./ # Download the artifacts to the root directory of the VM

  # Transfer the files to the EC2 instance using SSH and Rsync
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/ package.json" # Source directory on the VM that will be transferred to the EC2 instance
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # IP address of the EC2 instance that will host the application
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # Username of the EC2 instance that will host the application
          TARGET: ${{ secrets.REMOTE_TARGET }} # Target directory on the EC2 instance that will host the application
          # EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: | # Commands to run before deployment
            whoami
            ls -al
          SCRIPT_AFTER: | # Commands to run after deployment
            cd ${{ secrets.REMOTE_TARGET }} 
            pm2 restart http-app || pm2 start app.js --name http-app 
            pm2 save
        # Restart the app if it's running, otherwise start it in the background using PM2
  # All credintials are stored in the secrets of the repository. The secrets are encrypted and can be used in the workflow without exposing them in the code.


        
